# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otelcol'
          scrape_interval: 10s
          static_configs:
            - targets: ['prometheus:9090']

exporters:
  debug:
  otlphttp/prometheus:
    endpoint: "http://prometheus:9090/api/v1/otlp"
    tls:
      insecure: true
  influxdb:
    endpoint: "http://influxdb:8086"
    org: "demo"
    bucket: "demo"
    token: "EIUUa7wzdFlvSOE79iTWwqhSO30vkIw289EY6cVyXs5U8SRY1nln36bPf4MHBaA6"
processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [otlphttp/prometheus, debug, influxdb]
