# /etc/grafana/provisioning/datasources/datasource.yaml
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    database: mydatabase
    user: grafana
    password: grafana
    isDefault: true
    jsonData:
      timeInterval: "5s"

  - name: Alertmanager
    type: alertmanager
    url: http://alertmanager:9093
    access: proxy
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: true